name: Build and Release

on:
  push:
    branches:
      - '**'  # Runs when you push a tag like v1.2.3

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven Packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Build with Maven
        run: mvn clean install --batch-mode

      - name: Gather all JARs and XMLs
        run: |
          mkdir -p release-files
          find . -type f -name "*.jar" -exec cp {} release-files/ \;
          cp releng/net.sourceforge.plantuml.composite/target/repository/compositeArtifacts.xml release-files/ || true
          cp releng/net.sourceforge.plantuml.composite/target/repository/compositeContent.xml release-files/ || true

      - name: Create ZIP of artifacts
        run: |
          cd release-files
          zip ../plantuml-release.zip *
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: plantuml-release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
