name: Build and Release

on:
  push:
    branches:
      - '**'  # Triggers on version tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Build with Maven
        run: mvn clean install --batch-mode

      # If your build process updates compositeArtifacts.xml and compositeContent.xml, skip the next step.
      # If you need to update them manually, add a script or modify this step.
      # - name: Update composite XMLs (example)
      #   run: |
      #     ./scripts/update-composite-xmls.sh

      - name: Gather JARs and XMLs for release
        run: |
          mkdir -p release-assets
          find . -name "*.jar" -exec cp {} release-assets/ \;
          cp releng/net.sourceforge.plantuml.composite/target/repository/compositeArtifacts.xml release-assets/ || true
          cp releng/net.sourceforge.plantuml.composite/target/repository/compositeContent.xml release-assets/ || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
